### ISSUE TITLE
Wayland support through a systemd service

### ISSUE THREAD

**Issue by Kommynct** [xslendix/libvinput#2]
Both kanata and keyd take keyboard input using a systemd service

https://github.com/CharaChorder/nexus/issues/148#issuecomment-2426612341

I'm wanting to use this under hyprland and unable because libvinput doesn't properly support wayland, kanata/keyd have the proper way to do this.

**Comment by slendidev** [comment]
It makes no sense for this to have a systemd service since this is a library. Applications that use this need to make themselves their own service if thats the goal.

**Comment by slendidev** [comment]
Wrong button.
